CREATE TABLE BUDGET.BUD_USUARIO (
    CON_USUARIO  NUMBER NOT NULL,
    COD_USUARIO  NVARCHAR2(60) NOT NULL,
    DSC_EMAIL    NVARCHAR2(60) NOT NULL,
    DSC_PASSWORD NVARCHAR2(20) NOT NULL
)
TABLESPACE DATOS_01;

COMMENT ON COLUMN BUDGET.BUD_USUARIO.CON_USUARIO IS
    'Consecutivo de usuario';

COMMENT ON COLUMN BUDGET.BUD_USUARIO.COD_USUARIO IS
    'Código de usuario';

COMMENT ON COLUMN BUDGET.BUD_USUARIO.DSC_EMAIL IS
    'Descripción del correo electrónico';

COMMENT ON COLUMN BUDGET.BUD_USUARIO.DSC_PASSWORD IS
    'Contraseña de ingreso';

CREATE INDEX BUDGET.BUD_USUARIO_IDX_01 ON
    BUDGET.BUD_USUARIO (
        CON_USUARIO
    ASC )
        TABLESPACE INDICES_01;

ALTER TABLE BUDGET.BUD_USUARIO ADD CONSTRAINT BUD_USUARIO_PK PRIMARY KEY ( CON_USUARIO );

CREATE SEQUENCE BUDGET.SEC_BUD_USUARIO START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER BUDGET.BUD_USUARIO_TRG_BII_01 BEFORE
    INSERT ON BUDGET.BUD_USUARIO
    FOR EACH ROW
    WHEN ( NEW.CON_USUARIO IS NULL )
BEGIN
    :NEW.CON_USUARIO := BUDGET.SEC_BUD_USUARIO.NEXTVAL;
END;
/