CREATE TABLE BUDGET.BUD_ROL (
    CON_ROL    NUMBER NOT NULL,
    COD_ROL    NVARCHAR2(20) NOT NULL,
    DSC_ROL    NVARCHAR2(60),
    LOG_ACTIVO CHAR(1)
)
TABLESPACE DATOS_01;

COMMENT ON COLUMN BUDGET.BUD_ROL.CON_ROL IS
    'Consecutivo de roles';

COMMENT ON COLUMN BUDGET.BUD_ROL.COD_ROL IS
    'Código del rol';

COMMENT ON COLUMN BUDGET.BUD_ROL.DSC_ROL IS
    'Descripción larga del rol';

COMMENT ON COLUMN BUDGET.BUD_ROL.LOG_ACTIVO IS
    'Log de activo del rol (1=si, 0=no)';

CREATE INDEX BUDGET.BUD_ROL_IDX_01 ON
    BUDGET.BUD_ROL (
        CON_ROL
    ASC )
        TABLESPACE INDICES_01;

ALTER TABLE BUDGET.BUD_ROL ADD CONSTRAINT BUD_ROL_PK PRIMARY KEY ( CON_ROL );

CREATE SEQUENCE BUDGET.SEC_BUD_ROL START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER BUDGET.BUD_ROL_TRG_BII_01 BEFORE
    INSERT ON BUDGET.BUD_ROL
    FOR EACH ROW
    WHEN ( NEW.CON_ROL IS NULL )
BEGIN
    :NEW.CON_ROL := BUDGET.SEC_BUD_ROL.NEXTVAL;
END;
/