CREATE TABLE BUDGET.BUD_USUARIO_ROL (
    CON_USUARIO_ROL NUMBER,
    CON_USUARIO     NUMBER NOT NULL,
    CON_ROL         NUMBER NOT NULL
)
TABLESPACE DATOS_01;

COMMENT ON COLUMN BUDGET.BUD_USUARIO_ROL.CON_USUARIO_ROL IS
    'Consecutivo de la tabla para seguimiento';

COMMENT ON COLUMN BUDGET.BUD_USUARIO_ROL.CON_USUARIO IS
    'Consecutivo del usuario';

COMMENT ON COLUMN BUDGET.BUD_USUARIO_ROL.CON_ROL IS
    'Consecutivo del rol';

CREATE INDEX BUDGET.BUD_USUARIO_ROL_IDX_01 ON
    BUDGET.BUD_USUARIO_ROL (
        CON_USUARIO_ROL
    ASC )
        TABLESPACE INDICES_01;

ALTER TABLE BUDGET.BUD_USUARIO_ROL
    ADD CONSTRAINT BUD_USUARIO_ROL_FK_01 FOREIGN KEY ( CON_USUARIO )
        REFERENCES BUDGET.BUD_USUARIO ( CON_USUARIO );

ALTER TABLE BUDGET.BUD_USUARIO_ROL
    ADD CONSTRAINT BUD_USUARIO_ROL_FK_02 FOREIGN KEY ( CON_ROL )
        REFERENCES BUDGET.BUD_ROL ( CON_ROL );