create or replace PACKAGE            PCK_DIGITACION IS

--PROCEDIMIENTO QUE LISTA LAS RESETAS POR NUMERO DE IDENTIFICACION
    PROCEDURE SP_RECETA_GETBY_IDENTIFICACION_DIGITACION (
        P_OUT_JSON              OUT CLOB,
        P_OUT_RESULTADO         OUT INTEGER,
        P_OUT_DETALLE           OUT VARCHAR2,
        P_IN_NUM_IDENTIFICACION IN VARCHAR2
    );

--PROCEDIMIENTO QUE LISTA LAS RESETAS POR ESTADO
    PROCEDURE SP_RECETAS_GETBY_COD_ESTADO (
        P_OUT_JSON      OUT CLOB,
        P_OUT_RESULTADO OUT INTEGER,
        P_OUT_DETALLE   OUT VARCHAR2,
        P_IN_COD_ESTADO IN NUMBER
    );

--PROCEDIMIENTO QUE CALCULA  LOS PRECIOS DE LOS ARTICULOS
    PROCEDURE SP_ARTICULO_PRECIO_GETBY_CONDICION_LENTE_ARO (
        P_OUT_JSON          OUT CLOB,
        P_OUT_RESULTADO     OUT INTEGER,
        P_OUT_DETALLE       OUT VARCHAR2,
        P_IN_TIPO_CONDICION IN NUMBER,
        P_IN_TIPO_LENTE     IN NUMBER,
        P_IN_TIPO_ARO       IN NUMBER
    );
    
--PROCEDIMIENTO QUE EVALUA EL LENTE Y ENVIA LA CONDICION 
    PROCEDURE SP_LENTE_GETBY_CONDICION (
        P_OUT_RESULTADO       OUT BOOLEAN,
        P_OUT_COD_GRADUACION  OUT INTEGER,
        P_OUT_VALIDA          OUT INTEGER,
        P_OUT_DETALLE         OUT VARCHAR2,
        P_TIPO_LENTE          IN VARCHAR2,
        P_CAN_DIOPTRIA_PRISMA IN VARCHAR2,
        P_DIOPTRIA_ADICION    IN VARCHAR2,
        P_DIOPTRIA_ESFERICO   IN VARCHAR2,
        P_DIOPTRIA_CILINDRO   IN VARCHAR2
    );

--PROCEDIMIENTO QUE ACTUALIZA LA CONDICION DEL LENTE
    PROCEDURE SP_LENTE_UPDATE_CONDICION(
        P_OUT_JSON      OUT CLOB,
        P_OUT_RESULTADO OUT INTEGER,
        P_OUT_DETALLE   OUT VARCHAR2,
        p_in_cod_receta_edus IN VARCHAR2
    );
    
--PROCEDIMIENTO QUE IDENTIFICA EL MATERIAL BASE DEL LENTE
    PROCEDURE SP_LENTE_CALCULO_BASE(
    P_OUT_VALIDADOR       OUT INTEGER,
    P_OUT_RESULTADO       OUT INTEGER,
    P_OUT_DETALLE         OUT VARCHAR2,
    P_ADICION   IN INTEGER,
    P_DIOPTRIA_ESFERICO   IN INTEGER,
    P_DIOPTRIA_CILINDRO   IN INTEGER
);

PROCEDURE SP_DETALLE_RECETA_GETBY_COD_RECETA (
        P_OUT_JSON      OUT CLOB,
        P_OUT_RESULTADO OUT INTEGER,
        P_OUT_DETALLE   OUT VARCHAR2,
        P_IN_COD_RECETA IN NUMBER
    );
FUNCTION FN_LENTE_CALCULO_BASE(
            P_ADICION   IN INTEGER,
            P_DIOPTRIA_ESFERICO   IN INTEGER,
            P_DIOPTRIA_CILINDRO   IN INTEGER
        ) RETURN NUMBER;
END;