--BORRAR TABLA
DROP TABLE SDAI_OWNER.SDAI_ARO CASCADE CONSTRAINTS;
COMMIT;
--BORRAR LA SECUENCIA PARA QUE NO PROBLEMAS
DROP SEQUENCE SDAI_OWNER.SEC_SDAI_ARO;
COMMIT;
--DESHABILITAR EL TRIGGER
DROP TRIGGER SDAI_OWNER.SDAI_ARO_BII_TRG_01;
COMMIT;

--CREACION TABLA
CREATE TABLE SDAI_OWNER.SDAI_ARO (
    COD_ARO              NUMBER NOT NULL,
    COD_SIGES            VARCHAR2(20) NOT NULL,
    TIP_ARO              NUMBER NOT NULL,
    DSC_ARO              VARCHAR2(255 CHAR) NOT NULL,
    CAN_TALLA	         NUMBER NOT NULL, 
    DSC_MODELO           VARCHAR2(255 CHAR) NOT NULL,
    COD_USUARIO_REGISTRO VARCHAR2(100 BYTE),
    FEC_REGISTRO	     DATE,
    COD_USUARIO_MODIFICO VARCHAR2(100 BYTE),
    FEC_MODIFICO	     DATE,
    LOG_ACTIVO	         CHAR(1 BYTE)
);

---COMENTARIOS DE LA TABLA AROS
COMMENT ON COLUMN SDAI_OWNER.SDAI_ARO.COD_ARO IS
    'codigo del aro.';
    
COMMENT ON COLUMN SDAI_OWNER.SDAI_ARO.COD_SIGES IS
    'Codigo de articulo en SIGES para compras';
    
COMMENT ON COLUMN SDAI_OWNER.SDAI_ARO.TIP_ARO IS
    'calificacion de los tipos de aro.';

COMMENT ON COLUMN SDAI_OWNER.SDAI_ARO.DSC_ARO IS
    'Descripcion de los aros.';

COMMENT ON COLUMN SDAI_OWNER.SDAI_ARO.CAN_TALLA IS
    'Tallas que tienen los aros.';    

COMMENT ON COLUMN SDAI_OWNER.SDAI_ARO.DSC_MODELO IS
    'Descripcion de los modelos de aros.';   

COMMENT ON COLUMN SDAI_OWNER.SDAI_ARO.COD_USUARIO_REGISTRO IS
    'Usuario que realiza el registro (auditoria).';

COMMENT ON COLUMN SDAI_OWNER.SDAI_ARO.FEC_REGISTRO IS
    'Fecha que se realiza el registro (auditoria)';

COMMENT ON COLUMN SDAI_OWNER.SDAI_ARO.COD_USUARIO_MODIFICO IS
    'Usuario que realiza la modificación del registro (auditoria)';

COMMENT ON COLUMN SDAI_OWNER.SDAI_ARO.FEC_MODIFICO IS
    'Fecha que se realiza la modificación del registro (auditoria)';

COMMENT ON COLUMN SDAI_OWNER.SDAI_ARO.LOG_ACTIVO IS
    'Estado del registro (Activo=0, Inactivo=1)';    
    
---INDEX
CREATE INDEX SDAI_OWNER.SDAI_ARO_PK ON SDAI_OWNER.SDAI_ARO (COD_ARO) TABLESPACE INDICES_01 ;
---PK
ALTER TABLE SDAI_OWNER.SDAI_ARO ADD PRIMARY KEY (COD_ARO) USING INDEX SDAI_OWNER.SDAI_ARO_PK  ENABLE;
---SECUENCIA
CREATE SEQUENCE SDAI_OWNER.SEC_SDAI_ARO START WITH 1 NOCACHE ORDER ;
---TRIGER
CREATE OR REPLACE TRIGGER SDAI_OWNER.SDAI_ARO_BII_TRG_01 
BEFORE INSERT ON SDAI_OWNER.SDAI_ARO 
FOR EACH ROW 
WHEN (NEW.COD_ARO IS NULL) 
BEGIN
:new.COD_ARO := SDAI_OWNER.SEC_SDAI_ARO.nextval;
end;

--INSERT
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-50-0001',11,'Armazones de pasta niña (o)',40,'CCSS-N1','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-50-0002',11,'Armazones de pasta niña (o)',40,'CCSS-N2','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-50-0003',11,'Armazones de pasta niña (o)',40,'CCSS-N3','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-50-0004',11,'Armazones de pasta niña (o)',40,'CCSS-N4','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-50-0005',11,'Armazones de pasta niña (o)',40,'CCSS-N5','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-50-0006',11,'Armazones de pasta niña (o)',40,'CCSS-N6','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-50-0007',11,'Armazones de pasta niña (o)',40,'CCSS-N7','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-50-0008',11,'Armazones de pasta niña (o)',40,'CCSS-N8','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-50-0009',11,'Armazones de pasta niña (o)',40,'CCSS-N9','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-50-0010',11,'Armazones de pasta niña (o)',40,'CCSS-N10','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-50-0011',11,'Armazones de pasta niña (o)',40,'CCSS-N13','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-50-0012',11,'Armazones de pasta niña (o)',40,'CCSS-N14','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-50-0013',11,'Armazones de pasta niña (o)',40,'CCSS-N16','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-50-0014',11,'Armazones de pasta niña (o)',40,'CCSS-N19','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-50-0015',11,'Armazones de pasta niña (o)',40,'CCSS-N20','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-50-0016',11,'Armazones de pasta niña (o)',40,'CCSS-N21','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-50-0017',11,'Armazones de pasta niña (o)',40,'CCSS-N22','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-50-0018',11,'Armazones de pasta niña (o)',40,'CCSS-N24','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-50-0019',11,'Armazones de pasta niña (o)',40,'CCSS-N25','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-50-0020',11,'Armazones de pasta niña (o)',40,'CCSS-N26','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-50-0021',11,'Armazones de pasta niña (o)',40,'CCSS-N27','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-51-0001',13,'Armazón completo (aro) oftálmico de  metal',50,'CCSS-M1','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-51-0002',13,'Armazón completo (aro) oftálmico de  metal',50,'CCSS-M2','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-51-0003',13,'Armazón completo (aro) oftálmico de  metal',50,'CCSS-M3','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-51-0004',13,'Armazón completo (aro) oftálmico de  metal',50,'CCSS-M4','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-51-0005',13,'Armazón completo (aro) oftálmico de  metal',50,'CCSS-M5','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-51-0006',13,'Armazón completo (aro) oftálmico de  metal',50,'CCSS-M6','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-51-0007',13,'Armazón completo (aro) oftálmico de  metal',50,'CCSS-M7','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-51-0008',13,'Armazón completo (aro) oftálmico de  metal',50,'CCSS-M8','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-51-0009',13,'Armazón completo (aro) oftálmico de  metal',50,'CCSS-M9','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-51-0010',13,'Armazón completo (aro) oftálmico de  metal',50,'CCSS-M10','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-51-0011',13,'Armazón completo (aro) oftálmico de  metal',52,'CCSS-M11','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-51-0012',13,'Armazón completo (aro) oftálmico de  metal',52,'CCSS-M12','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-51-0013',13,'Armazón completo (aro) oftálmico de  metal',52,'CCSS-M13','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-51-0014',13,'Armazón completo (aro) oftálmico de  metal',52,'CCSS-M14','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-51-0015',13,'Armazón completo (aro) oftálmico de  metal',52,'CCSS-M15','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-51-0016',13,'Armazón completo (aro) oftálmico de  metal',52,'CCSS-M16','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-51-0017',13,'Armazón completo (aro) oftálmico de  metal',52,'CCSS-M17','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-51-0018',13,'Armazón completo (aro) oftálmico de  metal',52,'CCSS-M18','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-51-0019',13,'Armazón completo (aro) oftálmico de  metal',52,'CCSS-M19','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-51-0020',13,'Armazón completo (aro) oftálmico de  metal',52,'CCSS-M20','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-51-0021',13,'Armazón completo (aro) oftálmico de metal',54,'CCSS-M21','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-51-0022',13,'Armazón completo (aro) oftálmico de metal',54,'CCSS-M22','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-51-0023',13,'Armazón completo (aro) oftálmico de metal',54,'CCSS-M23','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-51-0024',13,'Armazón completo (aro) oftálmico de metal',54,'CCSS-M24','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-51-0025',13,'Armazón completo (aro) oftálmico de metal',54,'CCSS-M25','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-51-0026',13,'Armazón completo (aro) oftálmico de metal',54,'CCSS-M26','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-51-0027',13,'Armazón completo (aro) oftálmico de metal',54,'CCSS-M27','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-51-0028',13,'Armazón completo (aro) oftálmico de metal',54,'CCSS-M28','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-51-0029',13,'Armazón completo (aro) oftálmico de metal',54,'CCSS-M29','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-51-0030',13,'Armazón completo (aro) oftálmico de metal',54,'CCSS-M30','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-51-0031',13,'Armazón completo (aro) oftálmico de  metal',56,'CCSS-M31','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-51-0032',13,'Armazón completo (aro) oftálmico de  metal',56,'CCSS-M32','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-51-0033',13,'Armazón completo (aro) oftálmico de  metal',56,'CCSS-M33','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-51-0034',13,'Armazón completo (aro) oftálmico de  metal',56,'CCSS-M34','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-51-0035',13,'Armazón completo (aro) oftálmico de  metal',56,'CCSS-M35','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-51-0036',13,'Armazón completo (aro) oftálmico de  metal',56,'CCSS-M36','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-51-0037',13,'Armazón completo (aro) oftálmico de  metal',56,'CCSS-M37','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-51-0038',13,'Armazón completo (aro) oftálmico de  metal',56,'CCSS-M38','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-51-0039',13,'Armazón completo (aro) oftálmico de  metal',56,'CCSS-M39','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-51-0040',13,'Armazón completo (aro) oftálmico de  metal',56,'CCSS-M40','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-52-0001',12,'Armazón completo (aro) oftálmico de pasta',46,'CCSS-P1','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-52-0002',12,'Armazón completo (aro) oftálmico de pasta',46,'CCSS-P2','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-52-0003',12,'Armazón completo (aro) oftálmico de pasta',46,'CCSS-P3','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-52-0004',12,'Armazón completo (aro) oftálmico de pasta',46,'CCSS-P4','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-52-0005',12,'Armazón completo (aro) oftálmico de pasta',46,'CCSS-P5','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-52-0006',12,'Armazón completo (aro) oftálmico de pasta',46,'CCSS-P6','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-52-0007',12,'Armazón completo (aro) oftálmico de pasta',46,'CCSS-P7','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-52-0008',12,'Armazón completo (aro) oftálmico de pasta',46,'CCSS-P8','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-52-0009',12,'Armazón completo (aro) oftálmico de pasta',46,'CCSS-P9','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-52-0010',12,'Armazón completo (aro) oftálmico de pasta',46,'CCSS-P10','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-52-0011',12,'Armazón completo (aro) oftálmico de  pasta',48,'CCSS-P11','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-52-0012',12,'Armazón completo (aro) oftálmico de  pasta',48,'CCSS-P12','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-52-0013',12,'Armazón completo (aro) oftálmico de  pasta',48,'CCSS-P13','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-52-0014',12,'Armazón completo (aro) oftálmico de  pasta',48,'CCSS-P14','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-52-0015',12,'Armazón completo (aro) oftálmico de  pasta',48,'CCSS-P15','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-52-0016',12,'Armazón completo (aro) oftálmico de  pasta',48,'CCSS-P16','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-52-0017',12,'Armazón completo (aro) oftálmico de  pasta',48,'CCSS-P17','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-52-0018',12,'Armazón completo (aro) oftálmico de  pasta',48,'CCSS-P18','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-52-0019',12,'Armazón completo (aro) oftálmico de  pasta',48,'CCSS-P19','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-52-0020',12,'Armazón completo (aro) oftálmico de  pasta',48,'CCSS-P20','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-52-0030',12,'Armazón completo (aro) oftálmico de pasta',50,'CCSS-P30','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-52-0031',12,'Armazón completo (aro) oftálmico de pasta',50,'CCSS-P31','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-52-0032',12,'Armazón completo (aro) oftálmico de pasta',50,'CCSS-P32','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-52-0033',12,'Armazón completo (aro) oftálmico de pasta',50,'CCSS-P33','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-52-0034',12,'Armazón completo (aro) oftálmico de pasta',50,'CCSS-P34','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-52-0035',12,'Armazón completo (aro) oftálmico de pasta',50,'CCSS-P35','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-52-0036',12,'Armazón completo (aro) oftálmico de pasta',50,'CCSS-P36','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-52-0037',12,'Armazón completo (aro) oftálmico de pasta',50,'CCSS-P37','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-52-0038',12,'Armazón completo (aro) oftálmico de pasta',50,'CCSS-P38','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-52-0039',12,'Armazón completo (aro) oftálmico de pasta',50,'CCSS-P39','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-52-0040',12,'Armazón completo (aro) oftálmico de pasta',52,'CCSS-P40','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-52-0041',12,'Armazón completo (aro) oftálmico de pasta',52,'CCSS-P41','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-52-0042',12,'Armazón completo (aro) oftálmico de pasta',52,'CCSS-P42','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-52-0043',12,'Armazón completo (aro) oftálmico de pasta',52,'CCSS-P43','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-52-0044',12,'Armazón completo (aro) oftálmico de pasta',52,'CCSS-P44','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-52-0045',12,'Armazón completo (aro) oftálmico de pasta',52,'CCSS-P45','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-52-0046',12,'Armazón completo (aro) oftálmico de pasta',52,'CCSS-P46','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-52-0047',12,'Armazón completo (aro) oftálmico de pasta',52,'CCSS-P47','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-52-0048',12,'Armazón completo (aro) oftálmico de pasta',52,'CCSS-P48','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-52-0049',12,'Armazón completo (aro) oftálmico de pasta',52,'CCSS-P49','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-52-0050',12,'Armazón completo (aro) oftálmico de pasta',54,'CCSS-P50','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-52-0051',12,'Armazón completo (aro) oftálmico de pasta',54,'CCSS-P51','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-52-0052',12,'Armazón completo (aro) oftálmico de pasta',54,'CCSS-P52','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-52-0053',12,'Armazón completo (aro) oftálmico de pasta',54,'CCSS-P53','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-52-0054',12,'Armazón completo (aro) oftálmico de pasta',54,'CCSS-P54','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-52-0055',12,'Armazón completo (aro) oftálmico de pasta',54,'CCSS-P55','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-52-0056',12,'Armazón completo (aro) oftálmico de pasta',54,'CCSS-P56','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-52-0057',12,'Armazón completo (aro) oftálmico de pasta',54,'CCSS-P57','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-52-0058',12,'Armazón completo (aro) oftálmico de pasta',54,'CCSS-P58','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-52-0059',12,'Armazón completo (aro) oftálmico de pasta',54,'CCSS-P59','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-52-0060',12,'Armazón completo (aro) oftálmico de pasta',54,'CCSS-P60','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-52-0061',12,'Armazón completo (aro) oftálmico de pasta',56,'CCSS-P61','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-52-0062',12,'Armazón completo (aro) oftálmico de pasta',56,'CCSS-P62','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-52-0063',12,'Armazón completo (aro) oftálmico de pasta',56,'CCSS-P63','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-52-0064',12,'Armazón completo (aro) oftálmico de pasta',56,'CCSS-P64','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-52-0065',12,'Armazón completo (aro) oftálmico de pasta',56,'CCSS-P65','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-52-0066',12,'Armazón completo (aro) oftálmico de pasta',56,'CCSS-P66','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-52-0067',12,'Armazón completo (aro) oftálmico de pasta',56,'CCSS-P67','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-52-0068',12,'Armazón completo (aro) oftálmico de pasta',56,'CCSS-P68','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-52-0069',12,'Armazón completo (aro) oftálmico de pasta',56,'CCSS-P69','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-52-0070',12,'Armazón completo (aro) oftálmico de pasta',56,'CCSS-P70','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_ARO (COD_SIGES, TIP_ARO, DSC_ARO, CAN_TALLA, DSC_MODELO, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-52-0071',12,'Armazón completo (aro) oftálmico de pasta',56,'CCSS-P71','Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
