
--BORRAR LA SECUENCIA PARA QUE NO PROBLEMAS
DROP SEQUENCE SDAI_OWNER.SEC_SDAI_BASE;
COMMIT;
--DESHABILITAR EL TRIGGER
DROP TRIGGER SDAI_OWNER.SDAI_BASE_BII_TRG_01;
COMMIT;

--BORRAR TABLA
DROP TABLE SDAI_OWNER.SDAI_BASE CASCADE CONSTRAINTS;
COMMIT;

--CREACION TABLA
CREATE TABLE SDAI_OWNER.SDAI_BASE (	
    COD_BASE                NUMBER,
    COD_SIGES               VARCHAR2(20) NOT NULL, 
    DSC_BASE                VARCHAR2(255 CHAR) NOT NULL,
	CAN_DIOPTRIA_ADICION    NUMBER, 
	CON_DIOPTRIA_BASE       NUMBER, 
	COD_USUARIO_REGISTRO    VARCHAR2(100 BYTE), 
	FEC_REGISTRO            DATE, 
	COD_USUARIO_MODIFICO    VARCHAR2(100 BYTE), 
	FEC_MODIFICO            DATE, 
	LOG_ACTIVO              CHAR(1 BYTE)
   );


---COMENTARIOS DE LA TABLA AROS
COMMENT ON COLUMN SDAI_OWNER.SDAI_BASE.COD_BASE IS
    'codigo del base.';
    
COMMENT ON COLUMN SDAI_OWNER.SDAI_BASE.COD_SIGES IS
    'Codigo de base en SIGES para compras';
    
COMMENT ON COLUMN SDAI_OWNER.SDAI_BASE.DSC_BASE IS
    'Descripcion de las bases.';

COMMENT ON COLUMN SDAI_OWNER.SDAI_BASE.CAN_DIOPTRIA_ADICION IS
    'Diptria de adicion.';

COMMENT ON COLUMN SDAI_OWNER.SDAI_BASE.CON_DIOPTRIA_BASE IS
    'Dioptria de base.';    

COMMENT ON COLUMN SDAI_OWNER.SDAI_BASE.COD_USUARIO_REGISTRO IS
    'Usuario que realiza el registro (auditoria).';

COMMENT ON COLUMN SDAI_OWNER.SDAI_BASE.FEC_REGISTRO IS
    'Fecha que se realiza el registro (auditoria)';

COMMENT ON COLUMN SDAI_OWNER.SDAI_BASE.COD_USUARIO_MODIFICO IS
    'Usuario que realiza la modificación del registro (auditoria)';

COMMENT ON COLUMN SDAI_OWNER.SDAI_BASE.FEC_MODIFICO IS
    'Fecha que se realiza la modificación del registro (auditoria)';

COMMENT ON COLUMN SDAI_OWNER.SDAI_BASE.LOG_ACTIVO IS
    'Estado del registro (Activo=0, Inactivo=1)';   


---INDEX
CREATE INDEX SDAI_OWNER.SDAI_BASE_PK ON SDAI_OWNER.SDAI_BASE (COD_BASE) TABLESPACE INDICES_01 ;
---PK
ALTER TABLE SDAI_OWNER.SDAI_BASE ADD PRIMARY KEY (COD_BASE) USING INDEX SDAI_OWNER.SDAI_BASE_PK  ENABLE;
---SECUENCIA
CREATE SEQUENCE SDAI_OWNER.SEC_SDAI_BASE START WITH 1 NOCACHE ORDER ;
---TRIGER
CREATE OR REPLACE TRIGGER SDAI_OWNER.SDAI_BASE_BII_TRG_01 
BEFORE INSERT ON SDAI_OWNER.SDAI_BASE 
FOR EACH ROW 
WHEN (NEW.COD_BASE IS NULL) 
BEGIN
:new.COD_BASE := SDAI_OWNER.SEC_SDAI_BASE.nextval;
end;
COMMIT;

Insert into SDAI_OWNER.SDAI_BASE (COD_SIGES, DSC_BASE, CAN_DIOPTRIA_ADICION, CON_DIOPTRIA_BASE, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-36-0001','LENT PLAST SIMPLE SEMITERM  BAS PLA',0,0,'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_BASE (COD_SIGES, DSC_BASE, CAN_DIOPTRIA_ADICION, CON_DIOPTRIA_BASE, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-36-0002','LENT PLAST SIMPLE SEMITERM  BAS 1.00',0,1,'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_BASE (COD_SIGES, DSC_BASE, CAN_DIOPTRIA_ADICION, CON_DIOPTRIA_BASE, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-36-0003','LENT PLAST SIMPLE SEMITERM  BAS 2.00',0,2,'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_BASE (COD_SIGES, DSC_BASE, CAN_DIOPTRIA_ADICION, CON_DIOPTRIA_BASE, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-36-0004','LENT PLAST SIMPLE SEMITERM  BAS 4.00',0,4,'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_BASE (COD_SIGES, DSC_BASE, CAN_DIOPTRIA_ADICION, CON_DIOPTRIA_BASE, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-36-0005','LENT PLAST SIMPLE SEMITERM  BAS 6.00',0,6,'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_BASE (COD_SIGES, DSC_BASE, CAN_DIOPTRIA_ADICION, CON_DIOPTRIA_BASE, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-36-0006','LENT PLAST SIMPLE SEMITERM  BAS 8.00',0,8,'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_BASE (COD_SIGES, DSC_BASE, CAN_DIOPTRIA_ADICION, CON_DIOPTRIA_BASE, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-36-0007','LENT PLAST SIMPLE SEMITERM BAS 10.00',0,10,'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_BASE (COD_SIGES, DSC_BASE, CAN_DIOPTRIA_ADICION, CON_DIOPTRIA_BASE, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-35-0001','LENT PLAST BIFOC SEMITERM AD +100 BAS 2',100,2,'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);

Insert into SDAI_OWNER.SDAI_BASE (COD_SIGES, DSC_BASE, CAN_DIOPTRIA_ADICION, CON_DIOPTRIA_BASE, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-35-0002','LENT PLAST BIFOC SEMITERM AD +100 BAS 4',100,4,'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_BASE (COD_SIGES, DSC_BASE, CAN_DIOPTRIA_ADICION, CON_DIOPTRIA_BASE, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-35-0003','LENT PLAST BIFOC SEMITERM AD +100 BAS 6',100,6,'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_BASE (COD_SIGES, DSC_BASE, CAN_DIOPTRIA_ADICION, CON_DIOPTRIA_BASE, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-35-0004','LENT PLAST BIFOC SEMITERM AD +100 BAS 8',100,8,'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_BASE (COD_SIGES, DSC_BASE, CAN_DIOPTRIA_ADICION, CON_DIOPTRIA_BASE, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-35-0005','LENT PLAST BIFOC SEMITERM AD +100 BAS 10',100,10,'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_BASE (COD_SIGES, DSC_BASE, CAN_DIOPTRIA_ADICION, CON_DIOPTRIA_BASE, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-35-0006','LENT PLAST BIFOC SEMITERM AD +125 BAS 2',125,2,'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_BASE (COD_SIGES, DSC_BASE, CAN_DIOPTRIA_ADICION, CON_DIOPTRIA_BASE, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-35-0007','LENT PLAST BIFOC SEMITERM AD +125 BAS 4',125,4,'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_BASE (COD_SIGES, DSC_BASE, CAN_DIOPTRIA_ADICION, CON_DIOPTRIA_BASE, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-35-0008','LENT PLAST BIFOC SEMITERM AD +125 BAS 6',125,6,'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_BASE (COD_SIGES, DSC_BASE, CAN_DIOPTRIA_ADICION, CON_DIOPTRIA_BASE, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-35-0009','LENT PLAST BIFOC SEMITERM AD +125 BAS 8',125,8,'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_BASE (COD_SIGES, DSC_BASE, CAN_DIOPTRIA_ADICION, CON_DIOPTRIA_BASE, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-35-0010','LENT PLAST BIFOC SEMITERM AD +125 BAS 10',125,10,'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_BASE (COD_SIGES, DSC_BASE, CAN_DIOPTRIA_ADICION, CON_DIOPTRIA_BASE, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-35-0011','LENT PLAST BIFOC SEMITERM AD +150 BAS 2',150,2,'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_BASE (COD_SIGES, DSC_BASE, CAN_DIOPTRIA_ADICION, CON_DIOPTRIA_BASE, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-35-0012','LENT PLAST BIFOC SEMITERM AD +150 BAS 4',150,4,'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_BASE (COD_SIGES, DSC_BASE, CAN_DIOPTRIA_ADICION, CON_DIOPTRIA_BASE, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-35-0013','LENT PLAST BIFOC SEMITERM AD +150 BAS 6',150,6,'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_BASE (COD_SIGES, DSC_BASE, CAN_DIOPTRIA_ADICION, CON_DIOPTRIA_BASE, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-35-0014','LENT PLAST BIFOC SEMITERM AD +150 BAS 8',150,8,'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_BASE (COD_SIGES, DSC_BASE, CAN_DIOPTRIA_ADICION, CON_DIOPTRIA_BASE, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-35-0015','LENT PLAST BIFOC SEMITERM AD +150 BAS 10',150,10,'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_BASE (COD_SIGES, DSC_BASE, CAN_DIOPTRIA_ADICION, CON_DIOPTRIA_BASE, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-35-0016','LENT PLAST BIFOC SEMITERM AD +175 BAS 2',175,2,'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_BASE (COD_SIGES, DSC_BASE, CAN_DIOPTRIA_ADICION, CON_DIOPTRIA_BASE, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-35-0017','LENT PLAST BIFOC SEMITERM AD +175 BAS 4',175,4,'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_BASE (COD_SIGES, DSC_BASE, CAN_DIOPTRIA_ADICION, CON_DIOPTRIA_BASE, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-35-0018','LENT PLAST BIFOC SEMITERM AD +175 BAS 6',175,6,'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_BASE (COD_SIGES, DSC_BASE, CAN_DIOPTRIA_ADICION, CON_DIOPTRIA_BASE, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-35-0019','LENT PLAST BIFOC SEMITERM AD +175 BAS 8',175,8,'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_BASE (COD_SIGES, DSC_BASE, CAN_DIOPTRIA_ADICION, CON_DIOPTRIA_BASE, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-35-0020','LENT PLAST BIFOC SEMITERM AD +175 BAS 10',175,10,'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_BASE (COD_SIGES, DSC_BASE, CAN_DIOPTRIA_ADICION, CON_DIOPTRIA_BASE, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-35-0021','LENT PLAST BIFOC SEMITERM AD +200 BAS 2',200,2,'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_BASE (COD_SIGES, DSC_BASE, CAN_DIOPTRIA_ADICION, CON_DIOPTRIA_BASE, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-35-0022','LENT PLAST BIFOC SEMITERM AD +200 BAS 4',200,4,'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_BASE (COD_SIGES, DSC_BASE, CAN_DIOPTRIA_ADICION, CON_DIOPTRIA_BASE, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-35-0023','LENT PLAST BIFOC SEMITERM AD +200 BAS 6',200,6,'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_BASE (COD_SIGES, DSC_BASE, CAN_DIOPTRIA_ADICION, CON_DIOPTRIA_BASE, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-35-0024','LENT PLAST BIFOC SEMITERM AD +200 BAS 8',200,8,'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_BASE (COD_SIGES, DSC_BASE, CAN_DIOPTRIA_ADICION, CON_DIOPTRIA_BASE, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-35-0025','LENT PLAST BIFOC SEMITERM AD +200 BAS 10',200,10,'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_BASE (COD_SIGES, DSC_BASE, CAN_DIOPTRIA_ADICION, CON_DIOPTRIA_BASE, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-35-0026','LENT PLAST BIFOC SEMITERM AD +225 BAS 2',225,2,'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_BASE (COD_SIGES, DSC_BASE, CAN_DIOPTRIA_ADICION, CON_DIOPTRIA_BASE, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-35-0027','LENT PLAST BIFOC SEMITERM AD +225 BAS 4',225,4,'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_BASE (COD_SIGES, DSC_BASE, CAN_DIOPTRIA_ADICION, CON_DIOPTRIA_BASE, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-35-0028','LENT PLAST BIFOC SEMITERM AD +225 BAS 6',225,6,'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_BASE (COD_SIGES, DSC_BASE, CAN_DIOPTRIA_ADICION, CON_DIOPTRIA_BASE, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-35-0029','LENT PLAST BIFOC SEMITERM AD +225 BAS 8',225,8,'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_BASE (COD_SIGES, DSC_BASE, CAN_DIOPTRIA_ADICION, CON_DIOPTRIA_BASE, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-35-0030','LENT PLAST BIFOC SEMITERM AD +225 BAS 10',225,10,'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_BASE (COD_SIGES, DSC_BASE, CAN_DIOPTRIA_ADICION, CON_DIOPTRIA_BASE, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-35-0031','LENT PLAST BIFOC SEMITERM AD +250 BAS 2',250,2,'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_BASE (COD_SIGES, DSC_BASE, CAN_DIOPTRIA_ADICION, CON_DIOPTRIA_BASE, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-35-0032','LENT PLAST BIFOC SEMITERM AD +250 BAS 4',250,4,'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_BASE (COD_SIGES, DSC_BASE, CAN_DIOPTRIA_ADICION, CON_DIOPTRIA_BASE, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-35-0033','LENT PLAST BIFOC SEMITERM AD +250 BAS 6',250,6,'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_BASE (COD_SIGES, DSC_BASE, CAN_DIOPTRIA_ADICION, CON_DIOPTRIA_BASE, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-35-0034','LENT PLAST BIFOC SEMITERM AD +250 BAS 8',250,8,'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_BASE (COD_SIGES, DSC_BASE, CAN_DIOPTRIA_ADICION, CON_DIOPTRIA_BASE, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-35-0035','LENT PLAST BIFOC SEMITERM AD +250 BAS 10',250,10,'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_BASE (COD_SIGES, DSC_BASE, CAN_DIOPTRIA_ADICION, CON_DIOPTRIA_BASE, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-35-0036','LENT PLAST BIFOC SEMITERM AD +275 BAS 2',275,2,'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_BASE (COD_SIGES, DSC_BASE, CAN_DIOPTRIA_ADICION, CON_DIOPTRIA_BASE, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-35-0037','LENT PLAST BIFOC SEMITERM AD +275 BAS 4',275,4,'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_BASE (COD_SIGES, DSC_BASE, CAN_DIOPTRIA_ADICION, CON_DIOPTRIA_BASE, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-35-0038','LENT PLAST BIFOC SEMITERM AD +275 BAS 6',275,6,'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_BASE (COD_SIGES, DSC_BASE, CAN_DIOPTRIA_ADICION, CON_DIOPTRIA_BASE, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-35-0039','LENT PLAST BIFOC SEMITERM AD +275 BAS 8',275,8,'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_BASE (COD_SIGES, DSC_BASE, CAN_DIOPTRIA_ADICION, CON_DIOPTRIA_BASE, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-35-0040','LENT PLAST BIFOC SEMITERM AD +275 BAS 10',275,10,'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_BASE (COD_SIGES, DSC_BASE, CAN_DIOPTRIA_ADICION, CON_DIOPTRIA_BASE, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-35-0041','LENT PLAST BIFOC SEMITERM AD +300 BAS 2',300,2,'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_BASE (COD_SIGES, DSC_BASE, CAN_DIOPTRIA_ADICION, CON_DIOPTRIA_BASE, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-35-0042','LENT PLAST BIFOC SEMITERM AD +300 BAS 4',300,4,'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_BASE (COD_SIGES, DSC_BASE, CAN_DIOPTRIA_ADICION, CON_DIOPTRIA_BASE, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-35-0043','LENT PLAST BIFOC SEMITERM AD +300 BAS 6',300,6,'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_BASE (COD_SIGES, DSC_BASE, CAN_DIOPTRIA_ADICION, CON_DIOPTRIA_BASE, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-35-0044','LENT PLAST BIFOC SEMITERM AD +300 BAS 8',300,8,'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_BASE (COD_SIGES, DSC_BASE, CAN_DIOPTRIA_ADICION, CON_DIOPTRIA_BASE, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('2-91-35-0045','LENT PLAST BIFOC SEMITERM AD +300 BAS 10',300,10,'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);
Insert into SDAI_OWNER.SDAI_BASE (COD_SIGES, DSC_BASE, CAN_DIOPTRIA_ADICION, CON_DIOPTRIA_BASE, COD_USUARIO_REGISTRO, FEC_REGISTRO, COD_USUARIO_MODIFICO, FEC_MODIFICO, LOG_ACTIVO) values ('9-99-99-9999','NO TIENE BASE NI GRADUCION TERMINADA',999,99,'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),'Rafael Gamboa Molina (rggamboa)',TO_date('08/07/2022','DD/MM/YYYY'),1);