
--BORRAR LA SECUENCIA
drop sequence CORE_OWNER.SEC_CORE_CATALOGO;
commit;

--DESHABILITAR EL TRIGGER PARA QUE DEJE HACER LOS INSERT
alter trigger CORE_OWNER.CORE_CATALOGO_BII_TRG_01 disable;
commit;

--BORRAR LOS DATOS DE LA TABLA
delete from CORE_OWNER.CORE_CATALOGO;
commit;

--INSERT EN LA TABLA CATALOGO PARA SDAI
INSERT INTO CORE_OWNER.CORE_CATALOGO (COD_CATALOGO, DSC_CATALOGO, DSC_MODULO, COD_USUARIO_REGISTRO, FEC_REGISTRO, log_activo)  VALUES 
(1,'Estados de Agendas','DA','Claudio Gerardo Cordero Soto (ccorderos)',TO_date('29/03/2022','DD/MM/YYYY'),0);
COMMIT;

INSERT INTO CORE_OWNER.CORE_CATALOGO (COD_CATALOGO, DSC_CATALOGO, DSC_MODULO, COD_USUARIO_REGISTRO, FEC_REGISTRO, log_activo)  VALUES 
(2,'Estados de Digitación','DA','Claudio Gerardo Cordero Soto (ccorderos)',TO_date('29/03/2022','DD/MM/YYYY'),0);
COMMIT;

INSERT INTO CORE_OWNER.CORE_CATALOGO (COD_CATALOGO, DSC_CATALOGO, DSC_MODULO, COD_USUARIO_REGISTRO, FEC_REGISTRO, log_activo)  VALUES 
(3,'Estados de Verificación','DA','Claudio Gerardo Cordero Soto (ccorderos)',TO_date('29/03/2022','DD/MM/YYYY'),0);
COMMIT;

INSERT INTO CORE_OWNER.CORE_CATALOGO (COD_CATALOGO,DSC_CATALOGO, DSC_MODULO, COD_USUARIO_REGISTRO, FEC_REGISTRO, log_activo)  VALUES 
(4,'Estados de Facturación','DA','Claudio Gerardo Cordero Soto (ccorderos)',TO_date('29/03/2022','DD/MM/YYYY'),0);
COMMIT;

INSERT INTO CORE_OWNER.CORE_CATALOGO (COD_CATALOGO,DSC_CATALOGO, DSC_MODULO, COD_USUARIO_REGISTRO, FEC_REGISTRO, log_activo)  VALUES 
(5,'Tipos de Graduación','DA','Claudio Gerardo Cordero Soto (ccorderos)',TO_date('29/03/2022','DD/MM/YYYY'),0);
COMMIT;

INSERT INTO CORE_OWNER.CORE_CATALOGO (COD_CATALOGO,DSC_CATALOGO, DSC_MODULO, COD_USUARIO_REGISTRO, FEC_REGISTRO, log_activo)  VALUES 
(6,'Tipos de Aros','DA','Claudio Gerardo Cordero Soto (ccorderos)',TO_date('29/03/2022','DD/MM/YYYY'),0);
COMMIT;

INSERT INTO CORE_OWNER.CORE_CATALOGO (COD_CATALOGO,DSC_CATALOGO, DSC_MODULO, COD_USUARIO_REGISTRO, FEC_REGISTRO, log_activo)  VALUES 
(7,'Tipos de Lentes','DA','Claudio Gerardo Cordero Soto (ccorderos)',TO_date('29/03/2022','DD/MM/YYYY'),0);
COMMIT;

INSERT INTO CORE_OWNER.CORE_CATALOGO (COD_CATALOGO,DSC_CATALOGO, DSC_MODULO, COD_USUARIO_REGISTRO, FEC_REGISTRO, log_activo)  VALUES 
(8,'Tipos de Material','DA','Claudio Gerardo Cordero Soto (ccorderos)',TO_date('29/03/2022','DD/MM/YYYY'),0);
COMMIT;

INSERT INTO CORE_OWNER.CORE_CATALOGO (COD_CATALOGO,DSC_CATALOGO, DSC_MODULO, COD_USUARIO_REGISTRO, FEC_REGISTRO, log_activo)  VALUES 
(9,'Tipos de Pagos','DA','Claudio Gerardo Cordero Soto (ccorderos)',TO_date('29/03/2022','DD/MM/YYYY'),0);
COMMIT;

INSERT INTO CORE_OWNER.CORE_CATALOGO (COD_CATALOGO,DSC_CATALOGO, DSC_MODULO, COD_USUARIO_REGISTRO, FEC_REGISTRO, log_activo)  VALUES 
(10,'Tipos de Identificación','DA','Claudio Gerardo Cordero Soto (ccorderos)',TO_date('29/03/2022','DD/MM/YYYY'),0);
COMMIT;

INSERT INTO CORE_OWNER.CORE_CATALOGO (COD_CATALOGO,DSC_CATALOGO, DSC_MODULO, COD_USUARIO_REGISTRO, FEC_REGISTRO, log_activo)  VALUES 
(11,'Condición de Lentes','DA','Claudio Gerardo Cordero Soto (ccorderos)',TO_date('29/03/2022','DD/MM/YYYY'),0);
COMMIT;

INSERT INTO CORE_OWNER.CORE_CATALOGO (COD_CATALOGO,DSC_CATALOGO, DSC_MODULO, COD_USUARIO_REGISTRO, FEC_REGISTRO, log_activo)  VALUES 
(12,'Tipos de Seguro','DA','Claudio Gerardo Cordero Soto (ccorderos)',TO_date('29/03/2022','DD/MM/YYYY'),0);
COMMIT;

INSERT INTO CORE_OWNER.CORE_CATALOGO (COD_CATALOGO,DSC_CATALOGO, DSC_MODULO, COD_USUARIO_REGISTRO, FEC_REGISTRO, log_activo)  VALUES 
(13,'Modelos de Lentes','DA','Claudio Gerardo Cordero Soto (ccorderos)',TO_date('29/03/2022','DD/MM/YYYY'),0);
COMMIT;

INSERT INTO CORE_OWNER.CORE_CATALOGO (COD_CATALOGO,DSC_CATALOGO, DSC_MODULO, COD_USUARIO_REGISTRO, FEC_REGISTRO, log_activo)  VALUES 
(14,'Tipos de Citas','DA','Claudio Gerardo Cordero Soto (ccorderos)',TO_date('29/03/2022','DD/MM/YYYY'),0);
COMMIT;

INSERT INTO CORE_OWNER.CORE_CATALOGO (COD_CATALOGO,DSC_CATALOGO, DSC_MODULO, COD_USUARIO_REGISTRO, FEC_REGISTRO, log_activo)  VALUES 
(15,'Tipo de Parámetro','DA','Claudio Gerardo Cordero Soto (ccorderos)',TO_date('29/03/2022','DD/MM/YYYY'),0);
COMMIT;

--INSERT EN LA TABLA CATALOGOS PARA SIOP
INSERT INTO CORE_OWNER.CORE_CATALOGO (COD_CATALOGO,DSC_CATALOGO, DSC_MODULO, COD_USUARIO_REGISTRO, FEC_REGISTRO, log_activo)  VALUES 
(16,'Estados de Verificación','OP','Claudio Gerardo Cordero Soto (ccorderos)',TO_date('29/03/2022','DD/MM/YYYY'),0);
COMMIT;

INSERT INTO CORE_OWNER.CORE_CATALOGO (COD_CATALOGO, DSC_CATALOGO, DSC_MODULO, COD_USUARIO_REGISTRO, FEC_REGISTRO, log_activo)  VALUES 
(17,'Tipos de Liner','OP','Claudio Gerardo Cordero Soto (ccorderos)',TO_date('29/03/2022','DD/MM/YYYY'),0);
COMMIT;

INSERT INTO CORE_OWNER.CORE_CATALOGO (COD_CATALOGO,DSC_CATALOGO, DSC_MODULO, COD_USUARIO_REGISTRO, FEC_REGISTRO, log_activo)  VALUES 
(18,'Tipos de Pie','OP','Claudio Gerardo Cordero Soto (ccorderos)',TO_date('29/03/2022','DD/MM/YYYY'),0);
COMMIT;


--HABILITAR EL TRIGGER
alter trigger CORE_OWNER.CORE_CATALOGO_BII_TRG_01 enable;
commit;

--CREAR LA SECUENCIA NUEVAMENTE EN EL NUMERO FINAL
CREATE SEQUENCE CORE_OWNER.SEC_CORE_CATALOGO START WITH 19 NOCACHE ORDER ;

CREATE OR REPLACE TRIGGER CORE_OWNER.CORE_CATALOGO_BII_TRG_01 
BEFORE INSERT ON CORE_OWNER.CORE_CATALOGO 
FOR EACH ROW 
WHEN (NEW.COD_CATALOGO IS NULL) 
BEGIN
:new.cod_catalogo := sec_CORE_CATALOGO.nextval;

end;
