--BORRAR LA SECUENCIA PARA QUE NO PROBLEMAS
drop sequence CORE_OWNER.SEC_CORE_TIPO;
commit;

--DESHABILITAR EL TRIGGER
alter trigger CORE_OWNER.CORE_TIPO_BII_TRG_01 disable;
commit;

--BORRAR LOS DATOS DE LA TABLA
delete from CORE_OWNER.CORE_TIPO;
commit;

-- INSERT EN LA TABLA 

INSERT INTO CORE_OWNER.CORE_TIPO ( TIP_TIPO, DSC_TIPO, COD_CATALOGO, COD_USUARIO_REGISTRO, FEC_REGISTRO, LOG_ACTIVO)
VALUES (1,'Bifocales',5,'Claudio Gerardo Cordero Soto (ccorderos)',TO_date('08/03/2022','DD/MM/YYYY'),0);
commit;

INSERT INTO CORE_OWNER.CORE_TIPO ( TIP_TIPO,DSC_TIPO, COD_CATALOGO, COD_USUARIO_REGISTRO, FEC_REGISTRO, LOG_ACTIVO)
VALUES (2,'Esfericos',5,'Claudio Gerardo Cordero Soto (ccorderos)',TO_date('08/03/2022','DD/MM/YYYY'),0);
commit;

INSERT INTO CORE_OWNER.CORE_TIPO ( TIP_TIPO, DSC_TIPO, COD_CATALOGO, COD_USUARIO_REGISTRO, FEC_REGISTRO, LOG_ACTIVO)
VALUES (3,'Cilindricos',5,'Claudio Gerardo Cordero Soto (ccorderos)',TO_date('08/03/2022','DD/MM/YYYY'),0);
commit;

INSERT INTO CORE_OWNER.CORE_TIPO (TIP_TIPO, DSC_TIPO, COD_CATALOGO, COD_USUARIO_REGISTRO, FEC_REGISTRO, LOG_ACTIVO)
VALUES (4,'Compuestos +/-',5,'Claudio Gerardo Cordero Soto (ccorderos)',TO_date('08/03/2022','DD/MM/YYYY'),0);
commit;

INSERT INTO CORE_OWNER.CORE_TIPO ( TIP_TIPO,DSC_TIPO, COD_CATALOGO, COD_USUARIO_REGISTRO, FEC_REGISTRO, LOG_ACTIVO)
VALUES (5,'Compuestos -/-',5,'Claudio Gerardo Cordero Soto (ccorderos)',TO_date('08/03/2022','DD/MM/YYYY'),0);
commit;

INSERT INTO CORE_OWNER.CORE_TIPO ( TIP_TIPO,DSC_TIPO, COD_CATALOGO, COD_USUARIO_REGISTRO, FEC_REGISTRO, LOG_ACTIVO)
VALUES (6,'Bifocal',13,'Claudio Gerardo Cordero Soto (ccorderos)',TO_date('08/03/2022','DD/MM/YYYY'),0);
commit;

INSERT INTO CORE_OWNER.CORE_TIPO ( TIP_TIPO,DSC_TIPO, COD_CATALOGO, COD_USUARIO_REGISTRO, FEC_REGISTRO, LOG_ACTIVO)
VALUES (7,'Lejos',13,'Claudio Gerardo Cordero Soto (ccorderos)',TO_date('08/03/2022','DD/MM/YYYY'),0);
commit;

INSERT INTO CORE_OWNER.CORE_TIPO ( TIP_TIPO,DSC_TIPO, COD_CATALOGO, COD_USUARIO_REGISTRO, FEC_REGISTRO, LOG_ACTIVO)
VALUES (8,'Cerca',13,'Claudio Gerardo Cordero Soto (ccorderos)',TO_date('08/03/2022','DD/MM/YYYY'),0);
commit;

INSERT INTO CORE_OWNER.CORE_TIPO (TIP_TIPO, DSC_TIPO, COD_CATALOGO, COD_USUARIO_REGISTRO, FEC_REGISTRO, LOG_ACTIVO)
VALUES (9,'Seguro por el Estado',17,'Claudio Gerardo Cordero Soto (ccorderos)',TO_date('08/03/2022','DD/MM/YYYY'),0);
commit;

INSERT INTO CORE_OWNER.CORE_TIPO ( TIP_TIPO,DSC_TIPO, COD_CATALOGO, COD_USUARIO_REGISTRO, FEC_REGISTRO, LOG_ACTIVO)
VALUES (10,'Asegurado Directo',17,'Claudio Gerardo Cordero Soto (ccorderos)',TO_date('08/03/2022','DD/MM/YYYY'),0);
commit;

INSERT INTO CORE_OWNER.CORE_TIPO ( TIP_TIPO, DSC_TIPO, COD_CATALOGO, COD_USUARIO_REGISTRO, FEC_REGISTRO, LOG_ACTIVO)
VALUES (11,'Pasta Niño(a)',6,'Claudio Gerardo Cordero Soto (ccorderos)',TO_date('08/03/2022','DD/MM/YYYY'),0);
commit;

INSERT INTO CORE_OWNER.CORE_TIPO ( TIP_TIPO, DSC_TIPO, COD_CATALOGO, COD_USUARIO_REGISTRO, FEC_REGISTRO, LOG_ACTIVO)
VALUES (12,'Pasta',6,'Claudio Gerardo Cordero Soto (ccorderos)',TO_date('08/03/2022','DD/MM/YYYY'),0);
commit;

INSERT INTO CORE_OWNER.CORE_TIPO ( TIP_TIPO, DSC_TIPO, COD_CATALOGO, COD_USUARIO_REGISTRO, FEC_REGISTRO, LOG_ACTIVO)
VALUES (13,'Metal',6,'Claudio Gerardo Cordero Soto (ccorderos)',TO_date('08/03/2022','DD/MM/YYYY'),0);
commit;

INSERT INTO CORE_OWNER.CORE_TIPO ( TIP_TIPO, DSC_TIPO, COD_CATALOGO, COD_USUARIO_REGISTRO, FEC_REGISTRO, LOG_ACTIVO)
VALUES (14,'Cédula identidad registro civil',10,'Claudio Gerardo Cordero Soto (ccorderos)',TO_date('08/03/2022','DD/MM/YYYY'),0);
commit;

INSERT INTO CORE_OWNER.CORE_TIPO ( TIP_TIPO, DSC_TIPO, COD_CATALOGO, COD_USUARIO_REGISTRO, FEC_REGISTRO, LOG_ACTIVO)
VALUES (15,'Tarjeta',9,'Claudio Gerardo Cordero Soto (ccorderos)',TO_date('08/03/2022','DD/MM/YYYY'),0);
commit;

INSERT INTO CORE_OWNER.CORE_TIPO ( TIP_TIPO, DSC_TIPO, COD_CATALOGO, COD_USUARIO_REGISTRO, FEC_REGISTRO, LOG_ACTIVO)
VALUES (16,'Efectivo',9,'Claudio Gerardo Cordero Soto (ccorderos)',TO_date('08/03/2022','DD/MM/YYYY'),0);
commit;

INSERT INTO CORE_OWNER.CORE_TIPO ( TIP_TIPO, DSC_TIPO, COD_CATALOGO, COD_USUARIO_REGISTRO, FEC_REGISTRO, LOG_ACTIVO)
VALUES (17,'Asegurado por el estado',9,'Claudio Gerardo Cordero Soto (ccorderos)',TO_date('08/03/2022','DD/MM/YYYY'),0);
commit;

INSERT INTO CORE_OWNER.CORE_TIPO ( TIP_TIPO, DSC_TIPO, COD_CATALOGO, COD_USUARIO_REGISTRO, FEC_REGISTRO, LOG_ACTIVO)
VALUES (18,'Extranjero con identificación CCSS',10,'Claudio Gerardo Cordero Soto (ccorderos)',TO_date('08/03/2022','DD/MM/YYYY'),0);
commit;

INSERT INTO CORE_OWNER.CORE_TIPO ( TIP_TIPO, DSC_TIPO, COD_CATALOGO, COD_USUARIO_REGISTRO, FEC_REGISTRO, LOG_ACTIVO)
VALUES (19,'Proceso - Proceso',11,'Claudio Gerardo Cordero Soto (ccorderos)',TO_date('08/03/2022','DD/MM/YYYY'),0);
commit;

INSERT INTO CORE_OWNER.CORE_TIPO ( TIP_TIPO, DSC_TIPO, COD_CATALOGO, COD_USUARIO_REGISTRO, FEC_REGISTRO, LOG_ACTIVO)
VALUES (20,'Terminando - Proceso',11,'Claudio Gerardo Cordero Soto (ccorderos)',TO_date('08/03/2022','DD/MM/YYYY'),0);
commit;

INSERT INTO CORE_OWNER.CORE_TIPO ( TIP_TIPO, DSC_TIPO, COD_CATALOGO, COD_USUARIO_REGISTRO, FEC_REGISTRO, LOG_ACTIVO)
VALUES (21,'Terminado - Terminado',11,'Claudio Gerardo Cordero Soto (ccorderos)',TO_date('08/03/2022','DD/MM/YYYY'),0);
commit;

INSERT INTO CORE_OWNER.CORE_TIPO ( TIP_TIPO, DSC_TIPO, COD_CATALOGO, COD_USUARIO_REGISTRO, FEC_REGISTRO, LOG_ACTIVO)
VALUES (22,'Lenticular simple',7,'Claudio Gerardo Cordero Soto (ccorderos)',TO_date('08/03/2022','DD/MM/YYYY'),0);
commit;

INSERT INTO CORE_OWNER.CORE_TIPO ( TIP_TIPO, DSC_TIPO, COD_CATALOGO, COD_USUARIO_REGISTRO, FEC_REGISTRO, LOG_ACTIVO)
VALUES (23,'Bifocal',7,'Claudio Gerardo Cordero Soto (ccorderos)',TO_date('08/03/2022','DD/MM/YYYY'),0);
commit;

INSERT INTO CORE_OWNER.CORE_TIPO ( TIP_TIPO, DSC_TIPO, COD_CATALOGO, COD_USUARIO_REGISTRO, FEC_REGISTRO, LOG_ACTIVO)
VALUES (24,'Simple',7,'Claudio Gerardo Cordero Soto (ccorderos)',TO_date('08/03/2022','DD/MM/YYYY'),0);
commit;

INSERT INTO CORE_OWNER.CORE_TIPO ( TIP_TIPO, DSC_TIPO, COD_CATALOGO, COD_USUARIO_REGISTRO, FEC_REGISTRO, LOG_ACTIVO)
VALUES (25,'Lenticular Bifocal',7,'Claudio Gerardo Cordero Soto (ccorderos)',TO_date('08/03/2022','DD/MM/YYYY'),0);
commit;

INSERT INTO CORE_OWNER.CORE_TIPO ( TIP_TIPO, DSC_TIPO, COD_CATALOGO, COD_USUARIO_REGISTRO, FEC_REGISTRO, LOG_ACTIVO)
VALUES (26,'Sin Aro',6,'Claudio Gerardo Cordero Soto (ccorderos)',TO_date('08/03/2022','DD/MM/YYYY'),0);
commit;

INSERT INTO CORE_OWNER.CORE_TIPO ( TIP_TIPO, DSC_TIPO, COD_CATALOGO, COD_USUARIO_REGISTRO, FEC_REGISTRO, LOG_ACTIVO)
VALUES (27,'Cilindros Transpuesto',5,'Claudio Gerardo Cordero Soto (ccorderos)',TO_date('08/03/2022','DD/MM/YYYY'),0);
commit;

INSERT INTO CORE_OWNER.CORE_TIPO ( TIP_TIPO, DSC_TIPO, COD_CATALOGO, COD_USUARIO_REGISTRO, FEC_REGISTRO, LOG_ACTIVO)
VALUES (28,'Compuestos +/- Transpuestos',5,'Claudio Gerardo Cordero Soto (ccorderos)',TO_date('08/03/2022','DD/MM/YYYY'),0);
commit;

INSERT INTO CORE_OWNER.CORE_TIPO ( TIP_TIPO, DSC_TIPO, COD_CATALOGO, COD_USUARIO_REGISTRO, FEC_REGISTRO, LOG_ACTIVO)
VALUES (29,'Compuestos -/- Transpuestos',5,'Claudio Gerardo Cordero Soto (ccorderos)',TO_date('08/03/2022','DD/MM/YYYY'),0);
commit;

INSERT INTO CORE_OWNER.CORE_TIPO ( TIP_TIPO, DSC_TIPO, COD_CATALOGO, COD_USUARIO_REGISTRO, FEC_REGISTRO, LOG_ACTIVO)
VALUES (30,'Plástico Blanco',8,'Claudio Gerardo Cordero Soto (ccorderos)',TO_date('08/03/2022','DD/MM/YYYY'),0);
commit;

INSERT INTO CORE_OWNER.CORE_TIPO ( TIP_TIPO, DSC_TIPO, COD_CATALOGO, COD_USUARIO_REGISTRO, FEC_REGISTRO, LOG_ACTIVO)
VALUES (31,'Policarbonato',8,'Claudio Gerardo Cordero Soto (ccorderos)',TO_date('08/03/2022','DD/MM/YYYY'),0);
commit;

INSERT INTO CORE_OWNER.CORE_TIPO ( TIP_TIPO, DSC_TIPO, COD_CATALOGO, COD_USUARIO_REGISTRO, FEC_REGISTRO, LOG_ACTIVO)
VALUES (32,'Fotocromático',8,'Claudio Gerardo Cordero Soto (ccorderos)',TO_date('08/03/2022','DD/MM/YYYY'),0);
commit;

INSERT INTO CORE_OWNER.CORE_TIPO ( TIP_TIPO, DSC_TIPO, COD_CATALOGO, COD_USUARIO_REGISTRO, FEC_REGISTRO, LOG_ACTIVO)
VALUES (33,'CCSS',14,'Claudio Gerardo Cordero Soto (ccorderos)',TO_date('08/03/2022','DD/MM/YYYY'),0);
commit;

INSERT INTO CORE_OWNER.CORE_TIPO ( TIP_TIPO, DSC_TIPO, COD_CATALOGO, COD_USUARIO_REGISTRO, FEC_REGISTRO, LOG_ACTIVO)
VALUES (34,'Privada',14,'Claudio Gerardo Cordero Soto (ccorderos)',TO_date('08/03/2022','DD/MM/YYYY'),0);
commit;

-- INSERT EN LA TABLA TIPOS PARA SIOP

INSERT INTO CORE_OWNER.CORE_TIPO ( TIP_TIPO, DSC_TIPO, COD_CATALOGO, COD_USUARIO_REGISTRO, FEC_REGISTRO, LOG_ACTIVO)
VALUES (35,'Liner Pin Recto TT',17,'Claudio Gerardo Cordero Soto (ccorderos)',TO_date('08/03/2022','DD/MM/YYYY'),0);
commit;

INSERT INTO CORE_OWNER.CORE_TIPO ( TIP_TIPO, DSC_TIPO, COD_CATALOGO, COD_USUARIO_REGISTRO, FEC_REGISTRO, LOG_ACTIVO)
VALUES (36,'Liner Pin Recto TF',17,'Claudio Gerardo Cordero Soto (ccorderos)',TO_date('08/03/2022','DD/MM/YYYY'),0);
commit;

INSERT INTO CORE_OWNER.CORE_TIPO ( TIP_TIPO, DSC_TIPO, COD_CATALOGO, COD_USUARIO_REGISTRO, FEC_REGISTRO, LOG_ACTIVO)
VALUES (37,'Liner Anillos Recto TT',17,'Claudio Gerardo Cordero Soto (ccorderos)',TO_date('08/03/2022','DD/MM/YYYY'),0);
commit;

INSERT INTO CORE_OWNER.CORE_TIPO ( TIP_TIPO, DSC_TIPO, COD_CATALOGO, COD_USUARIO_REGISTRO, FEC_REGISTRO, LOG_ACTIVO)
VALUES (38,'Liner Anillos Recto TF',17,'Claudio Gerardo Cordero Soto (ccorderos)',TO_date('08/03/2022','DD/MM/YYYY'),0);
commit;

INSERT INTO CORE_OWNER.CORE_TIPO ( TIP_TIPO, DSC_TIPO, COD_CATALOGO, COD_USUARIO_REGISTRO, FEC_REGISTRO, LOG_ACTIVO)
VALUES (39,'Liner Pin Cónico TT',17,'Claudio Gerardo Cordero Soto (ccorderos)',TO_date('08/03/2022','DD/MM/YYYY'),0);
commit;

INSERT INTO CORE_OWNER.CORE_TIPO ( TIP_TIPO, DSC_TIPO, COD_CATALOGO, COD_USUARIO_REGISTRO, FEC_REGISTRO, LOG_ACTIVO)
VALUES (40,'Liner Pin Cónico TF',17,'Claudio Gerardo Cordero Soto (ccorderos)',TO_date('08/03/2022','DD/MM/YYYY'),0);
commit;

INSERT INTO CORE_OWNER.CORE_TIPO ( TIP_TIPO, DSC_TIPO, COD_CATALOGO, COD_USUARIO_REGISTRO, FEC_REGISTRO, LOG_ACTIVO)
VALUES (41,'Liner Anillos Cónico TT',17,'Claudio Gerardo Cordero Soto (ccorderos)',TO_date('08/03/2022','DD/MM/YYYY'),0);
commit;

INSERT INTO CORE_OWNER.CORE_TIPO ( TIP_TIPO, DSC_TIPO, COD_CATALOGO, COD_USUARIO_REGISTRO, FEC_REGISTRO, LOG_ACTIVO)
VALUES (42,'Liner Anillos Cónico TF',17,'Claudio Gerardo Cordero Soto (ccorderos)',TO_date('08/03/2022','DD/MM/YYYY'),0);
commit;

INSERT INTO CORE_OWNER.CORE_TIPO ( TIP_TIPO, DSC_TIPO, COD_CATALOGO, COD_USUARIO_REGISTRO, FEC_REGISTRO, LOG_ACTIVO)
VALUES (43,'Pie Sach',18,'Claudio Gerardo Cordero Soto (ccorderos)',TO_date('08/03/2022','DD/MM/YYYY'),0);
commit;

INSERT INTO CORE_OWNER.CORE_TIPO ( TIP_TIPO, DSC_TIPO, COD_CATALOGO, COD_USUARIO_REGISTRO, FEC_REGISTRO, LOG_ACTIVO)
VALUES (44,'Pie Articulado',18,'Claudio Gerardo Cordero Soto (ccorderos)',TO_date('08/03/2022','DD/MM/YYYY'),0);
commit;

INSERT INTO CORE_OWNER.CORE_TIPO ( TIP_TIPO, DSC_TIPO, COD_CATALOGO, COD_USUARIO_REGISTRO, FEC_REGISTRO, LOG_ACTIVO)
VALUES (45,'Pie Carbono',18,'Claudio Gerardo Cordero Soto (ccorderos)',TO_date('08/03/2022','DD/MM/YYYY'),0);
commit;


--CREAR SECUENCIA NUEVAMENTE
CREATE SEQUENCE CORE_OWNER.SEC_CORE_TIPO START WITH 46 NOCACHE    ORDER ;

--HABILITAR EL TRIGGER
alter trigger CORE_OWNER.CORE_TIPO_BII_TRG_01 enable;
commit;


CREATE OR REPLACE TRIGGER CORE_OWNER.CORE_TIPO_BII_TRG_01 
BEFORE INSERT ON CORE_OWNER.CORE_TIPO 
FOR EACH ROW 
WHEN (NEW.TIP_TIPO IS NULL) 
BEGIN
:new.TIP_TIPO := sec_CORE_TIPO.nextval;

end;
/


