
--BORRAR TABLA
DROP TABLE SDAI_OWNER.SDAI_TONO CASCADE CONSTRAINTS;
COMMIT;
--BORRAR LA SECUENCIA PARA QUE NO PROBLEMAS
DROP SEQUENCE SDAI_OWNER.SEC_SDAI_TONO;
COMMIT;
--DESHABILITAR EL TRIGGER
DROP TRIGGER SDAI_OWNER.SDAI_TONO_BII_TRG_01;
COMMIT;

--CREACION TABLA
CREATE TABLE SDAI_OWNER.SDAI_TONO (
    COD_TONO             NUMBER NOT NULL,
    COD_SIGES            VARCHAR2(20) NOT NULL,
    DSC_TONO             VARCHAR2(255 CHAR) NOT NULL,
    COD_USUARIO_REGISTRO VARCHAR2(100 BYTE),
    FEC_REGISTRO	     DATE,
    COD_USUARIO_MODIFICO VARCHAR2(100 BYTE),
    FEC_MODIFICO	     DATE,
    LOG_ACTIVO	         CHAR(1 BYTE)
);

---COMENTARIOS DE LA TABLA AROS
COMMENT ON COLUMN SDAI_OWNER.SDAI_TONO.COD_TONO IS
    'codigo del tono.';
    
COMMENT ON COLUMN SDAI_OWNER.SDAI_TONO.COD_SIGES IS
    'Codigo de tono en SIGES para compras';
    
COMMENT ON COLUMN SDAI_OWNER.SDAI_TONO.DSC_TONO IS
    'Descripcion de tono.';

COMMENT ON COLUMN SDAI_OWNER.SDAI_TONO.COD_USUARIO_REGISTRO IS
    'Usuario que realiza el registro (auditoria).';

COMMENT ON COLUMN SDAI_OWNER.SDAI_TONO.FEC_REGISTRO IS
    'Fecha que se realiza el registro (auditoria)';

COMMENT ON COLUMN SDAI_OWNER.SDAI_TONO.COD_USUARIO_MODIFICO IS
    'Usuario que realiza la modificación del registro (auditoria)';

COMMENT ON COLUMN SDAI_OWNER.SDAI_TONO.FEC_MODIFICO IS
    'Fecha que se realiza la modificación del registro (auditoria)';

COMMENT ON COLUMN SDAI_OWNER.SDAI_TONO.LOG_ACTIVO IS
    'Estado del registro (Activo=0, Inactivo=1)';    
    
---INDEX
CREATE INDEX SDAI_OWNER.SDAI_TONO_PK ON SDAI_OWNER.SDAI_TONO (COD_TONO) TABLESPACE INDICES_01 ;
---PK
ALTER TABLE SDAI_OWNER.SDAI_TONO ADD PRIMARY KEY (COD_TONO) USING INDEX SDAI_OWNER.SDAI_TONO_PK  ENABLE;
---SECUENCIA
CREATE SEQUENCE SDAI_OWNER.SEC_SDAI_TONO START WITH 1 NOCACHE ORDER ;
---TRIGER
CREATE OR REPLACE TRIGGER SDAI_OWNER.SDAI_TONO_BII_TRG_01 
BEFORE INSERT ON SDAI_OWNER.SDAI_TONO 
FOR EACH ROW 
WHEN (NEW.COD_TONO IS NULL) 
BEGIN
:new.COD_TONO := SDAI_OWNER.SEC_SDAI_TONO.nextval;
end;
