--BORRAR TABLA
DROP TABLE SDAI_OWNER.SDAI_ARO CASCADE CONSTRAINTS;
COMMIT;
--BORRAR LA SECUENCIA PARA QUE NO PROBLEMAS
DROP SEQUENCE SDAI_OWNER.SEC_SDAI_ARO;
COMMIT;
--DESHABILITAR EL TRIGGER
DROP TRIGGER SDAI_OWNER.SDAI_ARO_BII_TRG_01;
COMMIT;

--CREACION TABLA
CREATE TABLE SDAI_OWNER.SDAI_ARO (
    COD_ARO              NUMBER NOT NULL,
    COD_SIGES            VARCHAR2(20) NOT NULL,
    TIP_ARO              NUMBER NOT NULL,
    DSC_ARO              VARCHAR2(255 CHAR) NOT NULL,
    CAN_TALLA	         NUMBER NOT NULL, 
    DSC_MODELO           VARCHAR2(255 CHAR) NOT NULL,
    COD_USUARIO_REGISTRO VARCHAR2(100 BYTE),
    FEC_REGISTRO	     DATE,
    COD_USUARIO_MODIFICO VARCHAR2(100 BYTE),
    FEC_MODIFICO	     DATE,
    LOG_ACTIVO	         CHAR(1 BYTE)
);

---COMENTARIOS DE LA TABLA AROS
COMMENT ON COLUMN SDAI_OWNER.SDAI_ARO.COD_ARO IS
    'codigo del aro.';
    
COMMENT ON COLUMN SDAI_OWNER.SDAI_ARO.COD_SIGES IS
    'Codigo de articulo en SIGES para compras';
    
COMMENT ON COLUMN SDAI_OWNER.SDAI_ARO.TIP_ARO IS
    'calificacion de los tipos de aro.';

COMMENT ON COLUMN SDAI_OWNER.SDAI_ARO.DSC_ARO IS
    'Descripcion de los aros.';

COMMENT ON COLUMN SDAI_OWNER.SDAI_ARO.CAN_TALLA IS
    'Tallas que tienen los aros.';    

COMMENT ON COLUMN SDAI_OWNER.SDAI_ARO.DSC_MODELO IS
    'Descripcion de los modelos de aros.';   

COMMENT ON COLUMN SDAI_OWNER.SDAI_ARO.COD_USUARIO_REGISTRO IS
    'Usuario que realiza el registro (auditoria).';

COMMENT ON COLUMN SDAI_OWNER.SDAI_ARO.FEC_REGISTRO IS
    'Fecha que se realiza el registro (auditoria)';

COMMENT ON COLUMN SDAI_OWNER.SDAI_ARO.COD_USUARIO_MODIFICO IS
    'Usuario que realiza la modificación del registro (auditoria)';

COMMENT ON COLUMN SDAI_OWNER.SDAI_ARO.FEC_MODIFICO IS
    'Fecha que se realiza la modificación del registro (auditoria)';

COMMENT ON COLUMN SDAI_OWNER.SDAI_ARO.LOG_ACTIVO IS
    'Estado del registro (Activo=0, Inactivo=1)';    
    
---INDEX
CREATE INDEX SDAI_OWNER.SDAI_ARO_PK ON SDAI_OWNER.SDAI_ARO (COD_ARO) TABLESPACE INDICES_01 ;
---PK
ALTER TABLE SDAI_OWNER.SDAI_ARO ADD PRIMARY KEY (COD_ARO) USING INDEX SDAI_OWNER.SDAI_ARO_PK  ENABLE;
---SECUENCIA
CREATE SEQUENCE SDAI_OWNER.SEC_SDAI_ARO START WITH 1 NOCACHE ORDER ;
---TRIGER
CREATE OR REPLACE TRIGGER SDAI_OWNER.SDAI_ARO_BII_TRG_01 
BEFORE INSERT ON SDAI_OWNER.SDAI_ARO 
FOR EACH ROW 
WHEN (NEW.COD_ARO IS NULL) 
BEGIN
:new.COD_ARO := SDAI_OWNER.SEC_SDAI_ARO.nextval;
end;
