
--BORRAR LA SECUENCIA PARA QUE NO PROBLEMAS
DROP SEQUENCE SDAI_OWNER.SEC_SDAI_BASE;
COMMIT;
--DESHABILITAR EL TRIGGER
DROP TRIGGER SDAI_OWNER.SDAI_BASE_BII_TRG_01;
COMMIT;

--BORRAR TABLA
DROP TABLE SDAI_OWNER.SDAI_BASE CASCADE CONSTRAINTS;
COMMIT;

--CREACION TABLA
CREATE TABLE SDAI_OWNER.SDAI_BASE (	
    COD_BASE                NUMBER,
    COD_SIGES               VARCHAR2(20) NOT NULL, 
    DSC_BASE                VARCHAR2(255 CHAR) NOT NULL,
	CAN_DIOPTRIA_ADICION    NUMBER, 
	CON_DIOPTRIA_BASE       NUMBER, 
	COD_USUARIO_REGISTRO    VARCHAR2(100 BYTE), 
	FEC_REGISTRO            DATE, 
	COD_USUARIO_MODIFICO    VARCHAR2(100 BYTE), 
	FEC_MODIFICO            DATE, 
	LOG_ACTIVO              CHAR(1 BYTE)
   );


---COMENTARIOS DE LA TABLA AROS
COMMENT ON COLUMN SDAI_OWNER.SDAI_BASE.COD_BASE IS
    'codigo del base.';
    
COMMENT ON COLUMN SDAI_OWNER.SDAI_BASE.COD_SIGES IS
    'Codigo de base en SIGES para compras';
    
COMMENT ON COLUMN SDAI_OWNER.SDAI_BASE.DSC_BASE IS
    'Descripcion de las bases.';

COMMENT ON COLUMN SDAI_OWNER.SDAI_BASE.CAN_DIOPTRIA_ADICION IS
    'Diptria de adicion.';

COMMENT ON COLUMN SDAI_OWNER.SDAI_BASE.CON_DIOPTRIA_BASE IS
    'Dioptria de base.';    

COMMENT ON COLUMN SDAI_OWNER.SDAI_BASE.COD_USUARIO_REGISTRO IS
    'Usuario que realiza el registro (auditoria).';

COMMENT ON COLUMN SDAI_OWNER.SDAI_BASE.FEC_REGISTRO IS
    'Fecha que se realiza el registro (auditoria)';

COMMENT ON COLUMN SDAI_OWNER.SDAI_BASE.COD_USUARIO_MODIFICO IS
    'Usuario que realiza la modificación del registro (auditoria)';

COMMENT ON COLUMN SDAI_OWNER.SDAI_BASE.FEC_MODIFICO IS
    'Fecha que se realiza la modificación del registro (auditoria)';

COMMENT ON COLUMN SDAI_OWNER.SDAI_BASE.LOG_ACTIVO IS
    'Estado del registro (Activo=0, Inactivo=1)';   


---INDEX
CREATE INDEX SDAI_OWNER.SDAI_BASE_PK ON SDAI_OWNER.SDAI_BASE (COD_BASE) TABLESPACE INDICES_01 ;
---PK
ALTER TABLE SDAI_OWNER.SDAI_BASE ADD PRIMARY KEY (COD_BASE) USING INDEX SDAI_OWNER.SDAI_BASE_PK  ENABLE;
---SECUENCIA
CREATE SEQUENCE SDAI_OWNER.SEC_SDAI_BASE START WITH 1 NOCACHE ORDER ;
---TRIGER
CREATE OR REPLACE TRIGGER SDAI_OWNER.SDAI_BASE_BII_TRG_01 
BEFORE INSERT ON SDAI_OWNER.SDAI_BASE 
FOR EACH ROW 
WHEN (NEW.COD_BASE IS NULL) 
BEGIN
:new.COD_BASE := SDAI_OWNER.SEC_SDAI_BASE.nextval;
end;
COMMIT;
