--BORRAR TABLA
DROP TABLE SDAI_OWNER.SDAI_RECETA CASCADE CONSTRAINTS;
COMMIT;
--BORRAR LA SECUENCIA PARA QUE NO PROBLEMAS.
DROP SEQUENCE SDAI_OWNER.SEC_SDAI_RECETA;
COMMIT;
--DESHABILITAR EL TRIGGER.
DROP TRIGGER SDAI_OWNER.SDAI_RECETA_BII_TRG_01;
COMMIT;

  CREATE TABLE SDAI_OWNER.SDAI_RECETA (	
    COD_RECETA NUMBER NOT NULL, 
	COD_RECETA_EDUS VARCHAR2(20 BYTE) NOT NULL, 
	FEC_RECETA DATE NOT NULL, 
	COD_UNIDAD_EMISION VARCHAR2(4 BYTE) NOT NULL, 
	COD_UNIDAD_ADSCRIPCION VARCHAR2(4 BYTE) NOT NULL, 
	TIP_IDENTIFICACION NUMBER NOT NULL, 
	NUM_IDENTIFICACION VARCHAR2(60 BYTE) NOT NULL, 
	TIP_LENTE NUMBER NOT NULL, 
	CAN_DIOPTRIAS_ESFERICO_DER VARCHAR2(6 CHAR) NOT NULL, 
	CAN_DIOPTRIAS_ESFERICO_IZQ VARCHAR2(6 CHAR) NOT NULL, 
	CAN_DIOPTRIAS_CILINDRICO_DER VARCHAR2(6 CHAR) NOT NULL, 
	CAN_DIOPTRIAS_CILINDRICO_IZQ VARCHAR2(6 CHAR) NOT NULL, 
	CAN_DIOPTRIAS_EJE_DER VARCHAR2(6 CHAR) NOT NULL, 
	CAN_DIOPTRIAS_EJE_IZQ VARCHAR2(6 CHAR) NOT NULL, 
	CAN_DIOPTRIAS_PRISMA_DER VARCHAR2(20 CHAR) NOT NULL, 
	CAN_DIOPTRIAS_PRISMA_IZQ VARCHAR2(20 CHAR) NOT NULL, 
	CAN_DIOPTRIAS_ADICION VARCHAR2(6 CHAR) NOT NULL, 
	CAN_DIOPTRIAS_DIST_PUPILAR VARCHAR2(6 CHAR) NOT NULL, 
	CAN_DIOPTRIAS_DIST_NASOPUPILAR VARCHAR2(6 CHAR) NOT NULL,
    CAN_ALTURA NUMBER NOT NULL,
    COD_ESTADO NUMBER NOT NULL, 
    TIP_MATERIAL_LENTE NUMBER,
    LOG_TENNIDO NUMBER,
    COD_TONO_LENTE NUMBER,
	DSC_TONO VARCHAR2(20 BYTE), 
	LOG_TERMINADO_DERECHO NUMBER, 
	LOG_TERMINADO_IZQUIERDO NUMBER, 
	COD_LENTE_DER NUMBER, 
	COD_LENTE_IZQ NUMBER,
    COD_ARTICULO NUMBER,
    COD_ARO_MATERIAL NUMBER,
    COD_ARO_MODELO NUMBER,
	OBS_RECETA VARCHAR2(255 BYTE), 
	DSC_JUSTIFICACION VARCHAR2(220 BYTE),
    MON_COSTO_TOTAL NUMBER, 
	COD_USUARIO_REGISTRO VARCHAR2(100 BYTE), 
	FEC_REGISTRO DATE, 
	COD_USUARIO_MODIFICO VARCHAR2(100 BYTE), 
	FEC_MODIFICO DATE, 
	LOG_ACTIVO CHAR(1 BYTE)
   ) 

COMMENT ON COLUMN SDAI_OWNER.SDAI_RECETA.COD_RECETA IS 
'Código de la receta, consecutivo del sistema';

COMMENT ON COLUMN SDAI_OWNER.SDAI_RECETA.COD_RECETA_EDUS IS 
'Código de referencia de la receta del EDUS recibida';

COMMENT ON COLUMN SDAI_OWNER.SDAI_RECETA.FEC_RECETA IS 
'Fecha de la receta del EDUS';

COMMENT ON COLUMN SDAI_OWNER.SDAI_RECETA.COD_UNIDAD_EMISION IS 
'Unidad programática que emite la receta (FK UP)';

COMMENT ON COLUMN SDAI_OWNER.SDAI_RECETA.COD_UNIDAD_ADSCRIPCION IS 
'Unidad de adscripción del paciente (FK UP)';

COMMENT ON COLUMN SDAI_OWNER.SDAI_RECETA.TIP_IDENTIFICACION IS 
'Tipo de identificación (nacional, extranjero, asegurado)';

COMMENT ON COLUMN SDAI_OWNER.SDAI_RECETA.NUM_IDENTIFICACION IS 
'Número de identificación del paciente (FK PERSONAS)';

COMMENT ON COLUMN SDAI_OWNER.SDAI_RECETA.TIP_LENTE IS 
'Tipo de lente de la receta (FK Tipos)';

COMMENT ON COLUMN SDAI_OWNER.SDAI_RECETA.CAN_DIOPTRIAS_ESFERICO_DER IS 
'Valor númerico de la esfera del ojo derecho';

COMMENT ON COLUMN SDAI_OWNER.SDAI_RECETA.CAN_DIOPTRIAS_ESFERICO_IZQ IS 
'Valor númerico de la esfera ojo izquierdo';

COMMENT ON COLUMN SDAI_OWNER.SDAI_RECETA.CAN_DIOPTRIAS_CILINDRICO_DER IS 
'Valor númerico del cilindro del ojo derecho';

COMMENT ON COLUMN SDAI_OWNER.SDAI_RECETA.CAN_DIOPTRIAS_CILINDRICO_IZQ IS 
'Valor númerico del cilindro del ojo izquierdo';

COMMENT ON COLUMN SDAI_OWNER.SDAI_RECETA.CAN_DIOPTRIAS_EJE_DER IS 
'Valor númerico del eje derecho';

COMMENT ON COLUMN SDAI_OWNER.SDAI_RECETA.CAN_DIOPTRIAS_EJE_IZQ IS 
'Valor númerico del ojo izquierdo';

COMMENT ON COLUMN SDAI_OWNER.SDAI_RECETA.CAN_DIOPTRIAS_PRISMA_DER IS 
'Valor númerico del prima derecho';

COMMENT ON COLUMN SDAI_OWNER.SDAI_RECETA.CAN_DIOPTRIAS_PRISMA_IZQ IS 
'Valor númerico del prima del ojo izquierdo';

COMMENT ON COLUMN SDAI_OWNER.SDAI_RECETA.CAN_DIOPTRIAS_ADICION IS 
'Valor númerico de la adición de los lentes';

COMMENT ON COLUMN SDAI_OWNER.SDAI_RECETA.CAN_DIOPTRIAS_DIST_PUPILAR IS 
'valor númerico de la distancia pupilar de los lentes';

COMMENT ON COLUMN SDAI_OWNER.SDAI_RECETA.CAN_DIOPTRIAS_DIST_NASOPUPILAR IS 
'Valor númerico de la distancia nasopupilar de los lentes';

COMMENT ON COLUMN SDAI_OWNER.SDAI_RECETA.CAN_ALTURA IS 
'Valor númerico de la altura de los lentes';

COMMENT ON COLUMN SDAI_OWNER.SDAI_RECETA.COD_ESTADO IS 
'Código del estado de la receta (FK ESTADOS)';

COMMENT ON COLUMN SDAI_OWNER.SDAI_RECETA.TIP_MATERIAL_LENTE IS 
'Tipo de material de los lentes (FK TIPOS)(Policarbonato/Fotocromático/Plástico Blanco)';

COMMENT ON COLUMN SDAI_OWNER.SDAI_RECETA.LOG_TENNIDO IS 
'Valor del teñido de los lentes ( si o no)';

COMMENT ON COLUMN SDAI_OWNER.SDAI_RECETA.COD_TONO_LENTE IS 
'Color del aro de los lentes (FK ARTICULO TENNIDO)';

COMMENT ON COLUMN SDAI_OWNER.SDAI_RECETA.DSC_TONO IS 
'Descripción del tono de los aros';

COMMENT ON COLUMN SDAI_OWNER.SDAI_RECETA.LOG_TERMINADO_DERECHO IS 
'Valor para ver si el lente derecho es terminado 1 o procesado 0';

COMMENT ON COLUMN SDAI_OWNER.SDAI_RECETA.LOG_TERMINADO_IZQUIERDO IS 
'Valor para ver si el lente izquierdo es terminado 1 o procesado 0';

COMMENT ON COLUMN SDAI_OWNER.SDAI_RECETA.COD_LENTE_DER IS 
'Código de la base o de la graduacion terminada DER';

COMMENT ON COLUMN SDAI_OWNER.SDAI_RECETA.COD_LENTE_IZQ IS 
'Código de la base o de la graduacion terminada IZQ';

COMMENT ON COLUMN SDAI_OWNER.SDAI_RECETA.COD_ARTICULO IS 
'Código del Articulo';

COMMENT ON COLUMN SDAI_OWNER.SDAI_RECETA.COD_ARO_MATERIAL IS 
'Código del material del Aro(Plastico/metal/Plastico nin)';

COMMENT ON COLUMN SDAI_OWNER.SDAI_RECETA.COD_ARO_MODELO IS 
'Código del armazon que indica el modelo del aro';

COMMENT ON COLUMN SDAI_OWNER.SDAI_RECETA.OBS_RECETA IS 
'Observaciones sobre la receta';

COMMENT ON COLUMN SDAI_OWNER.SDAI_RECETA.DSC_JUSTIFICACION IS 
'Justificacion de Receta';

COMMENT ON COLUMN SDAI_OWNER.SDAI_RECETA.MON_COSTO_TOTAL IS 
'Costo total de la producción de los lentes (ver detalles)';

COMMENT ON COLUMN SDAI_OWNER.SDAI_RECETA.COD_USUARIO_REGISTRO IS 
'Usuario que realiza el registro (auditoria)';

COMMENT ON COLUMN SDAI_OWNER.SDAI_RECETA.FEC_REGISTRO IS 
'Fecha que se realiza el registro (auditoria)';

COMMENT ON COLUMN SDAI_OWNER.SDAI_RECETA.COD_USUARIO_MODIFICO IS 
'Usuario que realiza la modificación del registro (auditoria)';

COMMENT ON COLUMN SDAI_OWNER.SDAI_RECETA.FEC_MODIFICO IS 
'Fecha que se realiza la modificación del registro (auditoria)';

COMMENT ON COLUMN SDAI_OWNER.SDAI_RECETA.LOG_ACTIVO IS 
'Estado del registro (Activo=0, Inactivo=1)';




--------------------------------------------------------
--  DDL for Index SDAI_RECETA_PK
--------------------------------------------------------

CREATE INDEX SDAI_OWNER.SDAI_RECETA_PK ON SDAI_OWNER.SDAI_RECETA (COD_RECETA) TABLESPACE INDICES_01 ;

--------------------------------------------------------
--  DDL for PK SDAI_RECETA_PK
--------------------------------------------------------

ALTER TABLE SDAI_OWNER.SDAI_RECETA ADD PRIMARY KEY (COD_RECETA) USING INDEX SDAI_OWNER.SDAI_RECETA_PK  ENABLE;

--------------------------------------------------------
--  DDL for Secuencia 
--------------------------------------------------------

CREATE SEQUENCE SDAI_OWNER.SEC_SDAI_RECETA START WITH 1 NOCACHE ORDER ;

--------------------------------------------------------
--  DDL for Trigger SDAI_RECETA_BII_TRG_01
--------------------------------------------------------

CREATE OR REPLACE TRIGGER SDAI_OWNER.SDAI_RECETA_BII_TRG_01 
BEFORE INSERT ON SDAI_OWNER.SDAI_RECETA 
FOR EACH ROW 
WHEN (NEW.COD_RECETA IS NULL) 
BEGIN
:new.COD_RECETA := SDAI_OWNER.SEC_SDAI_RECETA.nextval;
end;

